import { getMenu } from '../main/async';

it('should return menu items', async () => {
  const menu = await getMenu();
  expect(menu).toEqual({
    items: [
      {
        _id: '2',
        name: 'Breadsticks',
        description: 'Fresh bread topped with melted butter',
        price: 4.99,
        cooking_time: '4',
        __v: 0,
        flavors: [],
        options: [],
        sizes: [],
      },
      {
        _id: '3',
        name: '2 Litre of soda',
        description: 'Pepsi Products',
        price: 3.99,
        cooking_time: '1',
        __v: 0,
        flavors: [
          { id: 'pepsi', value: 'Pepsi', isValid: true, checked: true },
          {
            id: 'drpepper',
            value: 'Dr. Pepper',
            isValid: true,
            checked: false,
          },
          {
            id: 'mountaindew',
            value: 'Mountain Dew',
            isValid: true,
            checked: false,
          },
        ],
        options: [],
        sizes: [],
      },
      {
        _id: '5',
        name: 'Calzone',
        description: 'Folded Pizza',
        price: 4.99,
        cooking_time: '9',
        __v: 0,
        options: [
          {
            _id: '65655cfb6b28b80a86912d6b',
            name: 'Pepperoni',
            price: 1,
            checked: false,
          },
          {
            _id: '65655cfb6b28b80a86912d6c',
            name: 'Sausage',
            price: 1,
            checked: false,
          },
          {
            _id: '65655cfb6b28b80a86912d6d',
            name: 'Mushroom',
            price: 1,
            checked: false,
          },
        ],
        flavors: [],
        sizes: [],
      },
      {
        _id: '6',
        name: 'Chicken Fettuccine Alfredo',
        description: 'Fettuccine with Aflredo sauce and grilled chicken',
        price: 12.99,
        cooking_time: '15',
        __v: 0,
        flavors: [],
        options: [],
        sizes: [],
      },
      {
        _id: '7',
        name: 'Shrimp Ravioli',
        description:
          'Ravioli stuffed with shrimp and romano in white wine cream sauce',
        price: 15.99,
        cooking_time: '13',
        __v: 0,
        flavors: [],
        options: [],
        sizes: [],
      },
      {
        _id: '8',
        name: 'Strawberry Cheesecake',
        description: 'New York-style cheesecake topped with strawberry puree',
        price: 7.99,
        cooking_time: '1',
        __v: 0,
        flavors: [],
        options: [],
        sizes: [],
      },
      {
        _id: '9',
        name: 'Brewed Tea',
        description: 'Fresh brewed unsweetened tea',
        price: 1.99,
        cooking_time: '1',
        __v: 0,
        flavors: [
          { id: 'sweet', value: 'Sweet', isValid: true, checked: false },
          { id: 'unsweet', value: 'Unsweet', isValid: true, checked: true },
        ],
        sizes: [],
        options: [],
      },
      {
        _id: '10',
        name: 'Fresh Lemonade',
        description: 'Freshly made lemonade',
        price: 2.99,
        cooking_time: '1',
        __v: 0,
        flavors: [],
        options: [],
        sizes: [],
      },
      {
        _id: '0',
        name: 'Pizza',
        description: 'Cheese, bread, red sauce and toppings',
        price: 11.99,
        cooking_time: '10',
        __v: 0,
        options: [
          {
            _id: '65655cfb6b28b80a86912d6e',
            name: 'Pepperoni',
            price: 1,
            checked: false,
          },
          {
            _id: '65655cfb6b28b80a86912d6f',
            name: 'Sausage',
            price: 1,
            checked: false,
          },
          {
            _id: '65655cfb6b28b80a86912d70',
            name: 'Mushroom',
            price: 1,
            checked: false,
          },
        ],
        flavors: [],
        sizes: [
          {
            id: 'small',
            value: 'Small',
            isValid: true,
            price: 8.99,
            inches: 10,
            checked: false,
          },
          {
            id: 'medium',
            value: 'Medium',
            isValid: true,
            price: 11.99,
            inches: 14,
            checked: true,
          },
          {
            id: 'large',
            value: 'Large',
            isValid: true,
            price: 15.99,
            inches: 16,
            checked: false,
          },
        ],
      },
      {
        _id: '1',
        name: 'Spaghetti',
        description: 'Cooked noodles, red sauce, and parmesan',
        price: 6.99,
        cooking_time: '12',
        __v: 0,
        flavors: [],
        options: [],
        sizes: [],
      },
    ],
  });
});
